// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Member struct {
	User  *User  `json:"user"`
	Role  string `json:"role"`
	Title string `json:"title"`
}

type Org struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Institution string    `json:"institution"`
	OrgPicURL   *string   `json:"org_pic_url"`
	Members     []*Member `json:"members"`
}

type User struct {
	ID          string  `json:"id"`
	Username    string  `json:"username"`
	FirstName   string  `json:"firstName"`
	LastName    string  `json:"lastName"`
	Institution string  `json:"institution"`
	PfpURL      *string `json:"pfp_url"`
}
